- .circleci/config.yml
Subtle tweak but significant when we start writing more tests
- Cache key doesn't depend on branch, just pure checksum on package/lock.json
- Skip `npm ci` altogether if cache matches
Speedup is around 2x for a cached workflow
> Improve circleci caching

- src/app.scss
- src/app.tsx
- src/assets/_colors.scss
- src/components/text-box/text-box.scss
- src/components/text-box/text-box.test.tsx
- src/components/text-box/text-box.tsx
Two variants:
- light (default)
- dark
Philosophy: 
- same philosophy as the text area component
- consumer should subscribe to `onChange` and save the state on their own
> Add text box component

- src/app.scss
- src/app.tsx
- src/assets/_styles.scss
- src/components/button/button.scss
- src/components/header/header.scss
- src/components/header/header.tsx
- src/components/sidebar/sidebar.scss
- src/components/sidebar/sidebar.tsx
- src/index.scss
- I am not sure how we want to handle navigation yet 
-  For the demo, I assumed we can just have a state bool `showDecks` and this determines if we show the decks or cards of a deck page.
-  clicking `flashcard decks` in the sidebar will set it to true, and we could set it up so clicking edit on a deck could set it to false
- We can rework the links later to be a lot more sound
- There is also no handlers set up in the search bar in the header
- We can add the handlers and mock data for the demo
> added header and sidebar

- src/components/deck-editor/meta-data-editor/meta-data-editor.scss
- src/components/deck-editor/meta-data-editor/meta-data-editor.tsx
- src/components/text-area/text-area.scss
- src/components/text-area/text-area.test.tsx
- src/components/text-area/text-area.tsx
- src/components/text-box/text-box.tsx
- dark variant added to text-area component
- animate label as legend via `animateLabelAsLegend` prop (default: `true`)
- cleaned up some unused imports
> Text area dark variant and animate label as legend

- craco.config.ts
- package-lock.json
- package.json
Forgot I had this in a stale branch from a month ago, test if this works on your machine and we can merge it
- use `esbuild-loader` instead of `babel-loader` 
- `esbuild` is a JS bundler written in Golang (fast bc it isn't interpreted)
- on my PC, it speeds up builds (`npm start` or `npm run build`) and hot-reload by 50%
> Inject esbuild-loader using craco to speedup compile times

- public/index.html
- src/assets/icons/cancel-icon/cancel-icon.scss
- src/assets/icons/cancel-icon/cancel-icon.tsx
- src/components/deck-editor/meta-data-editor/meta-data-editor.tsx
- src/components/popup-modal/popup-modal.scss
- src/components/popup-modal/popup-modal.test.tsx
- src/components/popup-modal/popup-modal.tsx
- src/components/search-bar/search-bar.scss
- src/components/search-bar/search-bar.test.tsx
- src/components/search-bar/search-bar.tsx
- src/components/text-box/text-box.test.tsx
- src/hooks/use-focus-first.ts
- src/hooks/use-focus-trap.ts
- src/hooks/use-outside-click.ts
just gonna document everything I did here, perhaps a little too verbose but the more the merrier 🤷 
- new popup modal component
- **(lifted state):** consumer of modal handles `showTrigger` and `onClose`  
- **(optional prop):** close modal when clicking outside of the modal contents
- new `useFocusTrap` hook to force accessibility navigation (`Tab` key) inside a parent ref
- can repurpose/use this to select specific elements when tabbing in the `meta-data-editor`
- new `useFocusFirst` hook to auto-focus the first element inside a parent ref
- use React portals to render modal outside of parent DOM while still propagating events
- **advantages:** less style conflicts (z-index, absolute styling), less rerenders
- change `cancel-icon.svg` to `CancelIcon` component …
> Add popup modal

- src/components/bubble-divider/bubble-divider.scss
- src/components/bubble-divider/bubble-divider.tsx
- src/hooks/use-focus-first.ts
just a fix for a little bug i found while messing around, it made the dropdown cut off
- `overflow: hidden` causes absolute children to not break out
- solution: animate `overflow: hidden` and restore it on `transitionEnd` of visible
- why `transitionEnd`? restoring it at the beginning will make it show before the animation expands to the area
**before:**
**after:**
> Fix bubble divider overflow breaking children layout

- craco.config.ts
- package-lock.json
- package.json
- src/app.test.tsx
- src/app.tsx
- src/components/page-header/page-header.tsx
- src/components/sidebar/sidebar-routes.tsx
- src/components/sidebar/sidebar.scss
- src/components/sidebar/sidebar.tsx
- src/components/text-area/text-area.scss
- src/components/text-box/text-box.scss
- src/hooks/use-prompt.ts
- src/index.tsx
- src/pages/deck-editor/deck-editor.tsx
- src/pages/decks/flashcard-decks.tsx
- src/routes.tsx
yayyy, we actually have page navigation!!! 🎉 
- entire app route definitions are in `routes.tsx`
- sidebar links defined in `components/sidebar/sidebar-routes.tsx`
- removed a lot of callback props, routing handled in page components
- (e.g.) deck editor page now pulls `deckId` from the query param (/deck-editor/:deckId)
- prevent page navigation in deck-editor using workaround hook: `usePrompt(message: string, when: boolean)`
**side note...** what do we _actually_ want `go back` to do in the deck editor? go to home page, or actually go to the prev page? because this can cause issues if the user gets to the page directly instead of through our app.
https://user-images.githubusercontent.com/29434693/162596695-39a1c497-65db-4226-9f17-e3432b211d14.mp4
> Add page navigation using react-router-dom

- src/app.scss
- src/components/bubble-divider/bubble-divider.scss
- src/components/header/header.scss
- src/components/sidebar/sidebar.scss
- by creating a stacking context, we don't need to worry about elements occluding the header no matter their z-index
> created a stacking context for the page content

- src/components/deck-cover/deck-cover.tsx
- src/components/flashcard-set/flashcard-set.tsx
- src/components/header/header.tsx
- src/hooks/use-deck-editor.ts
- src/models/deck.ts
- src/models/mock/deck.mock.ts
- src/pages/deck-editor/deck-editor.test.tsx
- src/pages/deck-editor/deck-editor.tsx
- src/pages/deck-editor/meta-data-editor/meta-data-editor.test.tsx
- src/pages/deck-editor/meta-data-editor/meta-data-editor.tsx
- src/pages/decks/flashcard-decks.tsx
summary of changes: 
- combined all state changes in `DeckEditor` into a `useReducer`
- created a custom hook to wrap calls and state of new `useReducer`
- now business logic and bookkeeping are in an isolated module
-  added testing to `DeckEditor`
- additional testing is needed
- fetching deck
- deleting deck
- saving deck
- modified `Deck` to have `DeckMetaData` as a member
> added useDeckEditor hook

- .circleci/config.yml
unfortunately, our previous workflow `tests` passing doesn't mean that the app can be built 
for example, the refactor from Deck -> DeckMetadata caused some breaking changes in my PR, but it wasn't caught
this PR acts to:
- add a `build` job step
- parallelize it with our `unit-tests` job
> Add build step to circleci and parallelize it with tests

- .env
- src/helpers/api.ts
- src/hooks/api/use-cards-client.ts
- src/hooks/api/use-decks-client.ts
- src/hooks/api/use-fetch-wrapper.ts
- src/pages/decks/flashcard-decks.tsx
- Implement fetch wrapper with basic functionality, no JWT/auth tokens yet
- Changes to `useDeckClient` --> implement `getAllDecks`, `getPublicDecks`
---
- Cannot actually hit the endpoints in dev environment due to CORS
- To test, I copied the response from the endpoint
- We probably want to fix CORS on the backend and test if it actually works before merging
---
> Basic api requests and fetch decks for flashcard-decks page

- src/assets/icons/loading-icon/loading-icon.scss
- src/assets/icons/loading-icon/loading-icon.tsx
- src/components/loading-page/loading-page.scss
- src/components/loading-page/loading-page.tsx
added `LoadingIcon` and `LoadingPage`
`LoadingIcon` has three sizes: `small`, `medium`, and `large`
`LoadingPage` has a label that slides in on a delay for longer wait times
https://user-images.githubusercontent.com/39753553/163585002-9dd30ace-4809-4823-a63b-a6b169c5db09.mov
https://user-images.githubusercontent.com/39753553/163585043-02fc44f4-92b6-4722-9f5f-16fc5d0e5451.mov
> added loading icons

- package-lock.json
- package.json
- src/app.test.tsx
- src/app.tsx
- src/helpers/sort.ts
- src/hooks/api/use-decks-client.ts
- src/index.tsx
- src/models/deck.ts
- src/models/mock/deck.mock.ts
- src/pages/decks/flashcard-decks.tsx
- src/state/user-decks.ts
started the basis of using `Recoil` with this PR
**summary of Recoil and how it's used here:**
- `atoms` are the simplest form of state (key, value) pair
- access using `useRecoilState` or if you only need the setter/getter `useSetRecoilState`/`useRecoilValue` respectively
- `selectors` are derived states, they update when atoms they depend on change
- for example, sorted decks should update when the user deck **_or_** sort option selected changes
- (i.e.) in this PR,  `userDecksSortedState` depends on the atoms: `userDecksState` and `userDecksSortedState`
- just like React's `useState`, whenever one of the recoil state changes, the component that consumes it is rerendered
**summary of changes:**
- add extra properties to `DeckMetadata`, we need this to sort by last created, say... maybe …
> Decks recoil state

- package.json
- src/app.test.tsx
- src/components/button/button.test.tsx
- src/components/deck-cover/deck-cover.test.tsx
- src/components/drop-down-options/drop-down-options.test.tsx
- src/components/drop-down-options/options.mock.ts
- src/components/drop-down/drop-down.test.tsx
- src/components/flashcard-set/flashcard-set.test.tsx
- src/components/flashcard-set/flashcard-set.tsx
- src/components/flashcard/card-face/card-face.test.tsx
- src/components/flashcard/flashcard.test.tsx
- src/components/flip-tile/flip-tile.scss
- src/components/flip-tile/flip-tile.test.tsx
- src/components/flip-tile/flip-tile.tsx
- src/components/header/header.test.tsx
- src/components/loading-page/loading-page.test.tsx
- src/components/loading-page/loading-page.tsx
- src/components/page-header/page-header.scss
- src/components/page-header/page-header.test.tsx
- src/components/page-header/page-header.tsx
- src/components/progress-bar/progress-bar.scss
- src/components/progress-bar/progress-bar.test.tsx
- src/components/progress-bar/progress-bar.tsx
- src/components/search-bar/search-bar.test.tsx
- src/components/sidebar/sidebar.test.tsx
- src/pages/edit-deck-page/deck-editor/deck-editor.test.tsx
- src/pages/edit-deck-page/deck-editor/meta-data-editor/meta-data-editor.test.tsx
add tests for every component, a couple components aren't finished... (i.e. header) 
but we should test that it displays properly at the minimum
---
* notable changes aside from tests
- improve class names for `FlipTile`, `PageHeader`, `ProgressBar`
- add `labelDelay` as a prop for `LoadingPage`
- add `renderWithHistoryRouter` to easily test components that can change the URL 
- as an example, see: `sidebar.test.tsx`
- `handleUpClick` for `FlashcardSet` now wraps around properly when clicking on the first card (it use to just swap with last)
---
* also added `npm run coverage` to get a feeling of how well-tested we are
- this may be misleading since this coverage includes _helpers_, _hooks_, and _models_
before:
after:
> Add way too many tests

- src/components/deck-cover/deck-cover.tsx
- src/pages/decks/flashcard-decks.scss
- added deck cover animation when reordered 
- added text color transition for `add new deck` card
https://user-images.githubusercontent.com/39753553/164149673-f2e8e315-db41-4c20-aeb0-793178ca62cd.mov
> added deck cover transition

- src/app.tsx
- src/components/header/header.test.tsx
- src/components/header/header.tsx
- src/components/page-header/page-header.test.tsx
- src/components/page-header/page-header.tsx
- src/pages/edit-deck-page/deck-editor/deck-editor.test.tsx
- src/pages/edit-deck-page/deck-editor/deck-editor.tsx
- src/pages/edit-deck-page/edit-deck-page.tsx
- src/pages/view-deck-page/view-deck-page.tsx
- added deck nav in the search bar
- only when a user clicks on a drop-down option
- updated routing so `go back` when editing takes user back to `view deck` for existing decks
- if new user is taken back to `decks`
- parameterized `go back` label for `PageHeader` component 
- added and fixed tests
https://user-images.githubusercontent.com/39753553/164247982-9f8a8bea-a806-4e3c-917c-98e433c3db9f.mov
> Add deck nav in search bar

- package-lock.json
- src/components/drop-down-options/drop-down-options.test.tsx
- src/components/search-bar/search-bar.test.tsx
- src/helpers/test.ts
title; it also speeds up tests bc we no longer have to wait for `rAF` so win-win situation
> fix: use fake timers to resolve flaky dropdown options test

- src/components/drop-down-options/drop-down-options.test.tsx
- src/components/drop-down-options/drop-down-options.tsx
- src/components/drop-down-options/options.mock.ts
- src/components/drop-down/drop-down.tsx
- src/components/flashcard/card-face/card-face.tsx
- src/components/header/header.tsx
- src/components/language-drop-down/drop-down-options/language-drop-down.tsx
- src/components/search-bar/search-bar.tsx
- src/pages/decks/flashcard-decks.tsx
- src/state/user-decks.ts
Added stricter typing to the dropdowns. 
onOptionSelect can now infer the type from the given options. 
For arrays declared as const for the options, the type is exactly one of the provided options. 
If the options type is not strict (e.g. string[]) the option type will also be not strict (string following the example).
> added stricter typing to dropdown menu

- package-lock.json
- package.json
- src/app.test.tsx
- src/helpers/tests/validator.test.ts
- src/helpers/validator.ts
- src/hooks/api/use-fetch-wrapper.ts
- src/hooks/api/use-user-client.ts
- src/hooks/tests/use-fetch-wrapper.test.tsx
- src/hooks/use-local-storage.ts
- src/index.tsx
- src/jest.d.ts
- src/pages/edit-deck-page/deck-editor/deck-editor.test.tsx
- src/setupTests.ts
- src/state/init.ts
- src/state/oauth2-jwt.ts
extends our fetch-wrapper to prep for handling auth JWTs + some misc stuff
- now able to retry requests (by default once)
- if a request fails on the server (e.g. 401 due to invalid JWT), we have a place to refresh the token (currently a TODO)
- an attempt to log the user in will serialize the token to local storage
- default `localStorage` only allows strings, `useLocalStorage` abstraction allows objects
- the serialized token lives in a recoil atom
- if token in local storage when app first loads, it will be passed to the atom as a init step
- object schema validator (type-guards for objects)
- custom jasmine matcher `.toMatchPredicate(predicate)` to chain result of expectation to a predicate
- tests for the schema validator and fetch wrapper retries
> feat: fetch with auth-jwt headers

- public/index.html
an example rewrite of `/decks/1` -> `/` should now serve the right static files
> fix: add base href to avoid url-rewrite using resource url as base

- src/components/resource-loader/resource-loader.tsx
- src/routes.tsx
had a bit of a merge conflict between the JWT fetch wrapper and resource fetchers
the JWT PR added hooks to the fetch wrapper which caused a bug in the resource fetcher PR to surface.
specifically, the Rule of Hooks: [React doesn't allow hooks to be called outside of functional components / custom hooks](https://reactjs.org/docs/hooks-rules.html)
---
- make the resource fetchers act like `custom hooks`! where logic can be lazily evaluated, but hooks consumed immediately
- signature of resource fetchers are now `() => Promise<T>` 
- resource loader immediately invokes the resource fetcher for hooks, but the actual logic is wrapped in a closure to be invoked later
> fix: resolve invalid hook call in resource fetchers

- src/components/flashcard/card-face/card-face.tsx
- src/components/flashcard/flashcard.tsx
- src/components/read-only-flashcard-set/read-only-flashcard-set.tsx
- src/hooks/api/use-cards-client.ts
- src/hooks/use-play-card-audio.ts
- src/models/card-content.ts
- src/models/lazy-audio.ts
- src/models/mock/card-content.mock.ts
- users will likely not listen to all audio files nor even listen to any audio files at all
instead, we lazily load audio files when needed using the new `LazyAudio` wrapper 
**(read header comment in `lazy-audio.ts`, mini architecture discussion)**
- audio pauses and resumes correctly in a study session (need to reset active audio while waiting)
- in the deck viewer, starting another audio will stop any ongoing audio from playing
---
https://user-images.githubusercontent.com/29434693/188330736-ca7af785-dcbe-4ce1-8779-223dd5170a5b.mp4
https://user-images.githubusercontent.com/29434693/188330754-fb327439-11c3-43ae-b9d4-476371e8591f.mp4
> feat: lazily load audio files

- src/assets/_styles.scss
- src/components/header/header.scss
- src/components/registration-panel/registration-panel.scss
- src/components/registration-panel/registration-panel.tsx
- src/pages/landing-page/landing-page.scss
- src/pages/landing-page/landing-page.tsx
- src/pages/not-found-page/not-found-page.scss
---
- landing page has improved styling for smaller screens (respect to height)
- header no longer breaks out when width < 500px
- center 404 page text
> feat(css): improve landing page on smaller devices

- .vscode/settings.json
- src/helpers/func.ts
- src/hooks/api/use-cards-client.ts
- src/hooks/tests/use-spaced-repetition.test.ts
- src/hooks/use-spaced-repetition.ts
- src/models/card.ts
- src/models/mock/card.mock.ts
- src/setupTests.ts
- add workspace config for using `jest-runner` extension (codelens for tests)
- update card client (and interface) to deserialize dates from response
- implement spaced repetition using the leitner system
- **Implementation:**
- with a 5-box system (this can be configured relatively easily)
- interface allows requesting `N` number of cards from a deck for studying
- **Boxes:**
- the first box (BOX1) is a special box, it is always 'stale'
- each box is a 'tier' of some sort, with a configured date of when a card is marked stale
- (e.g.) cards in the last box (BOX5) are not stale until 2 weeks have occurred since the last study 
- **Scoring:**
- all cards initially have a score of 0, hence in BOX1.
- scoring a card correctly will increment the score, moving it up a box
- scoring incorrectly …
> feat: implement spaced repetition using the leitner system

- public/web.config
server has certifytheweb installed but to verify the certificate it needs to allow access the static route `/.well-known/…` (i.e. don’t rewrite it to `/`)
also added a rule to redirect to HTTPS if not
> feat: ssl and https redirect

- src/assets/_styles.scss
- src/assets/icons/hamburger-menu-icon/hamburger-menu-icon.scss
- src/assets/icons/hamburger-menu-icon/hamburger-menu-icon.tsx
- src/assets/svg/hamburger-menu.svg
- src/components/deck-cover/deck-cover.scss
- src/components/drop-down/drop-down.scss
- src/components/drop-down/drop-down.tsx
- src/components/flip-tile/flip-tile.scss
- src/components/header/header.scss
- src/components/header/header.tsx
- src/components/popup-modal/popup-modal.scss
- src/components/read-only-flashcard/read-only-flashcard.scss
- src/components/sidebar/sidebar.scss
- src/components/sidebar/sidebar.tsx
- src/components/text-area/text-area.tsx
- src/helpers/func.ts
- src/layouts/sidebar-layout/sidebar-layout.scss
- src/layouts/sidebar-layout/sidebar-layout.tsx
- src/pages/decks/flashcard-decks.scss
- src/pages/decks/flashcard-decks.tsx
- src/pages/edit-deck-page/deck-editor/deck-editor.scss
- src/pages/edit-deck-page/deck-editor/meta-data-editor/meta-data-editor.scss
- src/pages/edit-deck-page/deck-editor/meta-data-editor/meta-data-editor.tsx
- src/state/nav.ts
ok, so this has been long coming but most are pages are usable on mobile/tablet/laptop devices
description is not fully in depth since there's a lot of minor tweaks too, but here are the biggest changes:
- sidebar hides on smaller widths
- header responsive to display a navigation hamburger menu 
- you can hit this to toggle the sidebar
- it also automatically toggles itself off if resized to be larger again
- heading now reorganizes on smaller devices (discard changes was too long)
- description and import (popup) buttons wrap on smaller screens
---
https://user-images.githubusercontent.com/29434693/191437097-d4a0d7c3-cd6a-46a8-abb1-32fe5ce8ea2f.mp4
> feat: responsive navbar and deck editor

- src/assets/icons/correct-icon/correct-icon.tsx
- src/assets/icons/incorrect-icon/incorrect-icon.tsx
- src/assets/icons/kebab-menu-icon/kabab-menu-icon.scss
- src/assets/icons/kebab-menu-icon/kebab-menu-icon.tsx
- src/assets/icons/skipped-icon/skipped-icon.tsx
- src/components/drop-down-options/drop-down-options.test.tsx
- src/components/drop-down-options/drop-down-options.tsx
- src/components/drop-down-options/options.mock.ts
- src/components/drop-down/drop-down.tsx
- src/components/flashcard/card-face/card-menu/card-menu.tsx
- src/components/header/header.scss
- src/components/header/header.tsx
- src/components/kebab-menu/kebab-menu.tsx
- src/components/language-drop-down/drop-down-options/language-drop-down.tsx
- src/components/read-only-flashcard/read-only-flashcard.scss
- src/components/search-bar/search-bar.tsx
- src/layouts/sidebar-layout/sidebar-layout.scss
- src/layouts/sidebar-layout/sidebar-layout.tsx
- src/models/lesson-card.ts
- src/models/mock/card.mock.ts
- src/pages/decks/flashcard-decks.tsx
- src/pages/study-page/study-page.tsx
- src/pages/study-page/study-results-page/study-result-cards/study-result-cards.scss
- src/pages/study-page/study-results-page/study-result-cards/study-result-cards.test.tsx
- src/pages/study-page/study-results-page/study-result-cards/study-result-cards.tsx
- src/pages/study-page/study-results-page/study-results-page.scss
- src/pages/study-page/study-results-page/study-results-page.tsx
- src/pages/view-deck-page/view-deck-page.scss
- src/pages/view-deck-page/view-deck-page.tsx
- Added roles to `correct`, `incorrect`, and `skipped` icons for accessibility and testing
- Set `DropDownOption` generic to be on the `id` instead of `value`
- Added kebab menu to study results cards to override card outcome
- kinda plain, might polish in future
-  broke study-results-cards into a separate component
- Readonly cards now break into two lines for small screens
- Added index on view deck page cards to help tie card faces together  
https://user-images.githubusercontent.com/39753553/191891884-f35477aa-8d05-4632-8070-91b4c7f9d2f4.mov
> Added kebab menu to override outcome in Lesson Results Page

- package-lock.json
- package.json
- src/assets/_styles.scss
- src/components/drop-down/drop-down.tsx
- src/components/header/account-popup/account-popup.scss
- src/components/header/account-popup/account-popup.test.tsx
- src/components/header/account-popup/account-popup.tsx
- src/components/header/header.scss
- src/components/header/header.tsx
- src/components/header/welcome-user/welcome-user.scss
- src/components/header/welcome-user/welcome-user.test.tsx
- src/components/header/welcome-user/welcome-user.tsx
- src/components/kebab-menu/kebab-menu.tsx
- src/components/popup-modal/popup-modal.tsx
- src/components/search-bar/search-bar.tsx
- src/helpers/validator.ts
- src/hooks/api/use-fetch-wrapper.ts
- src/hooks/api/use-user-client.ts
- src/hooks/tests/use-fetch-wrapper.test.ts
- src/hooks/use-key-press.ts
- src/hooks/use-outside-click.ts
- src/pages/decks/flashcard-decks.scss
- src/pages/decks/flashcard-decks.tsx
- src/routing/paths.ts
- src/state/auth-jwt.ts
- adds the account popup
- can close when outside click or escape press
- updates header to show responsive account group 
- account pfp from Gravatar (defaults to unique 8-bit icon like github if not registered)
- new recoil selector (userInfoState) that has a dependency on the authJwt atom
- whenever the jwt updates, it asynchronously fetches the user info
- this is why the `log out` button is seen for a second, it's the `React.Suspense` fallback state
---
https://user-images.githubusercontent.com/29434693/191907829-11321d98-2520-4c0b-af57-af6ca57a5e62.mp4
> feat: add account popup

- src/helpers/promise.ts
- src/hooks/api/use-fetch-wrapper.ts
fixes a race condition between multiple refresh requests.
if the access token is expired and 2+ authorized requests are made at nearly the same time, all of them would try to refresh.
only one request at most should be refreshing and other ones (which got a 401) should be waiting until it completes
- add a promise lock (mutex) to the refresh
- if another requests tries to refresh but one is happening already:
- skip the refresh
- retry the original request when the promise lock resolves (i.e. refresh finishes)
> fix: add promise lock to requests during token refresh

- src/components/header/header.tsx
- src/components/registration-panel/registration-panel.tsx
- src/helpers/time.ts
- src/hooks/api/use-cards-client.ts
- src/hooks/api/use-decks-client.ts
- src/hooks/use-mounted-ref.ts
- src/hooks/use-play-card-audio.ts
- src/hooks/use-play-lesson.ts
- src/hooks/use-spaced-repetition.ts
- src/models/lazy-audio.ts
- src/models/mock/card.mock.ts
- src/pages/study-page/study-lesson-page/study-lesson-page.tsx
- src/pages/study-page/study-results-page/study-results-page.scss
- src/pages/study-page/study-results-page/study-results-page.tsx
- src/state/auth-jwt.ts
- src/state/user-decks.ts
- utilize spaced repetition when picking cards
- lesson size updated to be minimum of cards or 5 -- temporary until lesson config
- scores are updated when the `lesson finished` button is clicked
- **[bug fix]** you can no longer skip more than there are cards available
- **[bug fix]** stop lingering audio when lesson finishes by skipping or when clicking browser tab back button
- clicking on registration buttons in the header no longer resets the tab's history stack 
- dates from the server are serialized as UTC time (with assumption that server's time-zone stays UTC)
-  **[bug fix]** ensure listeners are registered before `audio.load()` is called
- resolves an issue where audio doesn't play if the audio file was too small
- to be specific, `durationAsync()` was never resolving since it …
> feat: update card scores when lesson is finished

- src/components/header/account-popup/account-popup.scss
- src/components/header/account-popup/account-popup.tsx
- src/components/header/header.tsx
- src/components/header/welcome-user/welcome-user.tsx
- src/helpers/validator.ts
- src/hooks/api/interfaces/card-data.ts
- src/hooks/api/interfaces/deck-data.ts
- src/hooks/api/use-cards-client.ts
- src/hooks/api/use-decks-client.ts
- src/hooks/use-deck-editor.ts
- src/models/card.ts
- src/pages/edit-deck-page/edit-deck-page.tsx
- src/pages/export-cards-popup/export-cards-popup.tsx
- src/pages/study-page/study-results-page/study-results-page.tsx
- prevent empty cards (both front & back empty) from being added/saved
- use the new batch endpoints for deck create, card edit/score update/create/delete
- prevent deck editor from sending empty requests (e.g. no cards deleted should avoid doing `Cards/Delete`)
- make account popup fixed when header is also fixed
> fix: improve endpoint robustness

- src/assets/_styles.scss
- src/components/deck-cover/deck-cover.scss
- src/components/flip-tile/flip-tile.tsx
- src/components/popup-modal/popup-modal.scss
- src/components/popup-modal/popup-modal.tsx
- src/components/study-flashcard/study-flashcard.scss
- src/components/study-flashcard/study-flashcard.tsx
- src/hooks/api/use-fetch-wrapper.ts
- src/hooks/use-deck-editor.ts
- src/pages/edit-deck-page/deck-editor/deck-editor.test.tsx
- src/pages/edit-deck-page/deck-editor/deck-editor.tsx
- src/pages/study-page/study-results-page/study-results-page.scss
- src/pages/view-deck-page/view-deck-page.scss
- fixes a bug introduced last PR where it wouldn't abort fetches on unmount if there hadn't been a refresh before
- i still can't reproduce the logging out bug, lmk if it occurs again and i'll look into it some more
- introduce `grid-center` which performs safe centering when the inner container overflows the parent
- introduce `multiline-ellipsis-overflow` which allows containers to describe the max lines before overflowing
- improve text overflow on these areas:
- flashcard decks
- view flashcard
- study page popup, study page (+ lesson card), and results page
- disable save button when there are no changes
- fix race condition caused by two requests modifying a deck
- can observe that sometimes when editing title+desc and adding cards, only the cards are updated
--- …
> fix: text overflow improvements and save button state

- src/components/deck-cover/deck-cover.test.tsx
- src/components/deck-cover/deck-cover.tsx
- src/components/study-flashcard/study-flashcard.tsx
- src/hooks/use-play-lesson.ts
- src/pages/_shared/study-config-popup/study-config-popup.scss
- src/pages/_shared/study-config-popup/study-config-popup.tsx
- src/pages/landing-page/landing-page.scss
- src/pages/study-page/study-lesson-page/study-lesson-page.tsx
- src/pages/view-deck-pages/view-personal-deck-page/view-personal-deck-page.tsx
- skipping or replaying cards no longer overwrite the previous outcome
- this works because now, we only apply the outcome style on the back of the card
- disable study buttons with there are no cards 
- prevent access to lesson if manually navigating to study page on a deck with no cards
> fix: keep lesson card outcomes on skip or replay

- src/components/drop-down-options/drop-down-options.scss
- src/components/drop-down-options/drop-down-options.tsx
- fix bug with ellipsis overflow selector on parent (options container)
- add ellipsis overflow to child (single option) as well
- wrap all options in a grid component that evenly distributes height
---
**(search box)**
**(card options)**
> fix: improve dropdown options styling

- src/helpers/types.ts
- src/hooks/api/use-cards-client.ts
- src/hooks/api/use-fetch-wrapper.ts
- fixes cards not being added when a new deck is created
- enforce fetch wrapper to only allow non-promises as payload to avoid future oopsies
> fix: await cards promise before passing as payload
