src/models/Card.ts
src/models/CardContent.ts
src/models/Deck.ts
src/models/DeckCategory.ts
src/models/Session.ts
src/models/User.ts

- Card, CardContent, Deck, DeckCategory, Session, User (WIP)
Subject to change as backend matures.

Add basic data models

---

src/App.scss
src/App.tsx
src/components/Button/Button.scss
src/components/Button/Button.tsx
src/components/DeckCover/DeckCover.scss
src/components/DeckCover/DeckCover.tsx
src/components/FlipTile/FlipTile.scss
src/components/FlipTile/FlipTile.tsx
src/components/ProgressBar/ProgressBar.tsx

Added initial flip tile and deck cover components

added_flip_tile_and_deck_cover_components

---

src/app.scss
src/assets/_colors.scss
src/components/button/button.scss

I standardized and named all colors in the mockups. I used those exact names in the partial file to easily map the colors we need.

added partial class and swapped in variables in other files

---

.vscode/settings.json
package-lock.json
src/app.scss
src/app.tsx
src/assets/_styles.scss
src/components/deck-cover/deck-cover.scss
src/components/deck-cover/deck-cover.tsx
src/components/drop-down/drop-down.scss
src/components/sidebar/sidebar.scss
src/models/mock/deck.mock.ts
src/pages/decks/flashcard-decks.scss
src/pages/decks/flashcard-decks.tsx

You can access the edit deck page by clicking on `+ add new decks` or using the sidebar
- Each deck cover flip tile can be individually flipped
- Dynamic grid on decks with scrollable
- No pagination or sorting yet, just visually here
https://user-images.githubusercontent.com/29434693/161339320-e3cda0ac-8621-44b7-98fd-9a051a75c97b.mp4

Add demo flashcard decks page

---

src/components/bubble-divider/bubble-divider.scss
src/components/bubble-divider/bubble-divider.test.tsx
src/components/bubble-divider/bubble-divider.tsx
src/components/deck-editor/meta-data-editor/meta-data-editor.tsx

https://user-images.githubusercontent.com/39753553/162257505-c23c5ba7-58d5-42df-bbb7-fb09fa476613.mov

finished cleaning up BubbleDivider

---

src/assets/icons/arrow/arrow.scss
src/components/drop-down/drop-down.scss
src/components/drop-down/drop-down.tsx

- updated arrow and dropdown variants

fixed dark and light variant inconsistencies

---

.vscode/settings.json
src/hooks/api/use-cards-client.ts
src/hooks/api/use-decks-client.ts
src/hooks/api/use-fetch-wrapper.ts

let me know if this is what you had in mind for these api clients
i'd also like some feedback on if you like the formatting i went with! 
i wasn't too sure on how to best organize things so we know what's available in the client
- idea is to have the interface and we implement the methods as we need to use them
- cards client 
- decks client
- fetch wrapper
* usage examples:
```ts
// with .then (if you're a boomer)
const decksClient = useDecksClient();
decksClient.addDeck(...).then((newDeck) => ...);
// with async and await
const decksClient = useDecksClient();
const newDeck = await decksClient.addDeck(...);
// with destructuring assignment
const { addDeck } = useDecksClient();
const newDeck = await addDeck(...);
```

Add api clients (part 1)

---

src/components/flashcard-set/flashcard-set.tsx
src/components/flashcard/flashcard.tsx
src/hooks/api/use-cards-client.ts
src/hooks/use-deck-editor.ts
src/pages/edit-deck-page/deck-editor/deck-editor.tsx

oof, that was a lot tougher than I was expecting lol
- added cards are now added to the bottom of the set
- automatically scroll to the added card if not in view
- automatically set a newly added card to be active
https://user-images.githubusercontent.com/39753553/163693703-066e4e70-80fd-4e0a-9388-e4bfe7899558.mov

added smooth scrolling to bottom for new cards

---

src/hooks/api/use-cards-client.ts
src/hooks/api/use-decks-client.ts
src/hooks/api/use-fetch-wrapper.ts
src/pages/edit-deck-page/deck-editor/deck-editor.tsx
src/pages/edit-deck-page/edit-deck-page.tsx
src/pages/view-deck-page/view-deck-page.tsx

- implemented add and delete deck with the associated routing
- delete endpoint is a little scuffed, but we can figure it out after the demo

Implement add delete in use decks client

---

src/hooks/api/use-cards-client.ts
src/hooks/api/use-decks-client.ts
src/hooks/use-deck-editor.ts
src/models/card-content.ts
src/pages/edit-deck-page/edit-deck-page.tsx

- implemented addCard, addCards, updateCard, updateCards, deleteCardById, deleteCardsById, and updateDeck
https://user-images.githubusercontent.com/39753553/164158901-893db92e-4c28-49ff-9175-36fb3654d104.mov

added crud methods for cards

---

src/pages/edit-deck-page/edit-deck-page.tsx
src/pages/not-found-page/not-found-page.scss
src/pages/not-found-page/not-found-page.tsx
src/routes.tsx

added 404 page and update routes

---

src/components/flashcard/card-face/card-face.test.tsx
src/components/flashcard/card-face/card-face.tsx
src/components/flashcard/flashcard.test.tsx
src/pages/edit-deck-page/deck-editor/deck-editor.test.tsx
src/pages/edit-deck-page/deck-editor/deck-editor.tsx
src/pages/view-deck-page/view-deck-page.scss
src/pages/view-deck-page/view-deck-page.tsx

- prevent save when title or desc is empty
- hide speaker and placeholder when a card is empty"
- add empty card set placeholder message in view decks page
- added tests

prevent save when title or desc 

---

.env
.gitignore
src/components/flashcard-set/flashcard-set.tsx
src/components/flashcard/card-face/card-face.tsx
src/components/flashcard/flashcard.tsx
src/helpers/api.ts
src/hooks/api/use-cards-client.ts
src/hooks/use-deck-editor.ts
src/models/card-content.ts

Retrieve audio from s3

---

src/hooks/api/use-fetch-wrapper.ts

relatively simple; `fetch` supports passing in a signal in which you can abort to cancel the fetch

feat: cancel ongoing fetches on unmount

---

src/hooks/api/use-fetch-wrapper.ts

---
**tl;dr** stale closures resulted in outdated values for the auth token after refresh
---
Using `useState` gives the state and its updater, if we pass the state to an async function / callback such that a closure is created, the state is captured once. 
Any further updates on it will refer to the now stale value. 
Furthermore, `setState` is async in nature, so there's no guarantee to when the state value actually updates.
A common solution to this is to use `useRef` which is reference-based, but afaik this isn't an easy drop in solution for Recoil.
Instead, I opted to drop the usage of stateful values in the fetch wrapper:
- it's suppose to pure/stateless, we shouldn't have any side effects
- grabbing the value directly from local storage makes more semantic sense

fix: remove usage of stateful jwt value causing stale closure

---

src/helpers/api.ts
src/hooks/api/use-cards-client.ts

- baud/faud are now presigned urls
- enforce https

feat: utilize presigned audio urls

---

src/assets/_colors.scss
src/components/header/header.tsx
src/components/registration-panel/registration-panel.scss
src/components/registration-panel/registration-panel.tsx
src/helpers/validator.ts
src/hooks/api/use-fetch-wrapper.ts
src/hooks/api/use-user-client.ts
src/layouts/already-authorized-layout/already-authorized-layout.tsx
src/layouts/authorized-route-layout/authorized-route-layout.tsx
src/models/register-user.ts
src/pages/sign-in-page/sign-in-page.tsx
src/pages/sign-up/sign-up-page.scss
src/pages/sign-up/sign-up-page.tsx
src/routing/paths.ts
src/routing/routes.tsx
src/state/auth-jwt.ts
src/state/user-decks.ts

- sign-up page reorganized form inputs
- sign-up page has form validation
- only simple validation on client side
- otherwise, complex ones handled on server (maybe client side should be more strict?)
- sign-in page works
- guard the registration pages if you are already signed in
https://user-images.githubusercontent.com/29434693/190529319-ea9eef24-ac94-4d42-8c8a-bc997acedf3c.mp4

feat: add user registration form validation

---

src/assets/_colors.scss
src/assets/_styles.scss
src/components/bubble-divider/bubble-divider.tsx
src/components/header/welcome-user/welcome-user.tsx
src/components/progress-bar/progress-bar.scss
src/pages/profile-page/profile-page.scss
src/pages/profile-page/profile-page.tsx
src/pages/study-page/study-lesson-page/study-lesson-page.tsx
src/routing/routes.tsx
src/routing/sidebar-routes.tsx

this PR expands on the profile features and adds the profile page
it doesn't follow the mock to a tee, but if you have any suggestions/changes requested, holler out
refer to the included video as the description of changes
---
https://user-images.githubusercontent.com/29434693/192081029-93e44c49-eaa9-496b-92e9-079cefb5f4ba.mp4

feat: add profile page

---

src/animations/up-toggle.tsx
src/assets/icons/hamburger-menu-icon/hamburger-menu-icon.tsx
src/components/kebab-menu/kebab-menu.tsx
src/components/radio-button-group/radio-button-group.scss
src/components/radio-button-group/radio-button-group.tsx
src/components/registration-panel/registration-panel.tsx
src/models/mock/card.mock.ts
src/pages/edit-deck-page/deck-editor/meta-data-editor/meta-data-editor.scss
src/pages/edit-deck-page/deck-editor/meta-data-editor/meta-data-editor.test.tsx
src/pages/edit-deck-page/deck-editor/meta-data-editor/meta-data-editor.tsx
src/pages/import-cards-popup/import-cards-popup.scss
src/pages/import-cards-popup/import-cards-popup.tsx
src/pages/sign-up/sign-up-page.tsx
src/pages/study-page/study-results-page/study-result-cards/study-result-cards.test.tsx
src/state/auth-jwt.ts
src/state/user-decks.ts

- Added generics to `RadioButtonGroup` to restrict id
- Added dark variant to `RadioButtonGroup`
- Tightened import cards popup types
- Added `RadioButtonGroup` to deck metadata editor

added radio button in meta deck editor

---

src/hooks/api/use-decks-client.ts
src/hooks/api/use-fetch-wrapper.ts

i hope this fixes the sign out problem
if it ever happens again, can you send me the console logs?

fix: clear promise lock on resolve

---

src/layouts/sidebar-layout/sidebar-layout.scss
src/layouts/sidebar-layout/sidebar-layout.tsx
src/pages/not-found-page/not-found-page.tsx
src/routing/routes.tsx

this was the least intrusive solution i could think of
lmk if you see a better way, i'm not too convinced this was the best
---
https://user-images.githubusercontent.com/29434693/194444689-11da43dd-c8ea-4300-86f6-4cebbd5f8f21.mp4

feat: show sidebar on 404 page if user is signed in

---

src/hooks/api/use-fetch-wrapper.ts

fix: prevent fetch from aborting during refresh

---

src/components/bubble-tag-list/_bubble-tag-colors.scss
src/components/bubble-tag-list/bubble-tag-list.scss
src/components/bubble-tag-list/bubble-tag-list.tsx
src/pages/view-deck-pages/shared-view-deck-page.ts
src/pages/view-deck-pages/view-personal-deck-page/view-personal-deck-page.tsx
src/pages/view-deck-pages/view-public-deck-page/view-public-deck-page.tsx
src/scss.d.ts

add variable bubble styling

---

src/assets/_colors.scss
src/components/popup-modal/popup-modal.tsx
src/components/popup-video-player/popup-video-player.scss
src/components/popup-video-player/popup-video-player.tsx
src/hooks/api/use-public-resources.ts
src/hooks/use-search-categories.ts
src/pages/profile-page/public-profile-page/public-profile-page.tsx
src/pages/study-page/study-lesson-page/study-lesson-page.scss
src/pages/study-page/study-lesson-page/study-lesson-page.tsx

- Autoplay on open
https://user-images.githubusercontent.com/39753553/204118485-4a2dd894-1152-4edc-9b8f-5d521a56c1aa.mov

add lesson intro video

---

src/components/header/header.tsx
src/components/registration-panel/registration-panel.scss
src/components/registration-panel/registration-panel.tsx
src/pages/decks-page/flashcard-decks.scss
src/pages/decks-page/flashcard-decks.tsx
src/pages/landing-page/landing-page.tsx
src/pages/study-page/study-results-page/study-results-page.tsx

- prevent navigation to landing page if logged in (hate to do it, but it makes sense)
- flashcard decks now has a loading indicator bc sometimes it takes forever
- fix infinite loading if `finish lesson` 
- `study again` also saves lesson results now

feat: overall flow improvements
